import { useEffect, useMemo, useRef, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, CloudOff, Download, FileUp, History, Home, Printer, RefreshCw, Settings, SkipForward, Undo2, Wifi } from 'lucide-react';
const START='2026-08-24', END='2027-06-09', STORE='art-pwa-v4';
const templates={1:['Free','Free','Cantin','Alston'],2:['Graham','Horne','Evans','Free'],3:['EBS 2','Fray','Ward','Edwards'],4:['Jackson','Free','Wells','Reece'],5:['Kane','Radford','Free','Rogers'],6:['Trogdon','Hearley','ECS','Free']};
const periods=[['8:00 - 8:30','Hallway Duty (not 4th grade)'],['8:50 - 9:35','4th'],['9:55 - 10:40',null],['10:50 - 11:35',null],['11:35 - 12:10','Lunch'],['12:10 - 12:55',null],['12:55 - 1:40',null],['1:40 - 2:30','5th'],['2:30 - 3:00','Clean Up / Prepare for carpool'],['3:00 - 3:30','Afternoon Carpool']];
const closures={'2026-09-07':'Holiday','2026-09-21':'Teacher Workday','2026-10-12':'Teacher Workday','2026-11-03':'Teacher Workday','2026-11-11':'Holiday','2026-11-25':'Vacation Day','2026-11-26':'Holiday','2026-11-27':'Holiday','2026-12-21':'Teacher Workday','2026-12-22':'Teacher Workday','2026-12-23':'Vacation Day','2026-12-24':'Holiday','2026-12-25':'Holiday','2026-12-28':'Holiday','2026-12-29':'Vacation Day','2026-12-30':'Vacation Day','2026-12-31':'Vacation Day','2027-01-01':'Holiday','2027-01-18':'Holiday','2027-01-19':'Teacher Workday','2027-02-15':'Teacher Workday','2027-03-10':'Teacher Workday','2027-03-26':'Holiday','2027-03-29':'Vacation Day','2027-03-30':'Vacation Day','2027-03-31':'Vacation Day','2027-04-01':'Vacation Day','2027-04-02':'Vacation Day','2027-04-05':'Teacher Workday','2027-05-17':'Teacher Workday','2027-05-31':'Holiday'};
const builtIn=['2026-09-11'];
const D=s=>{const[y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}, I=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`, A=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x}, F=s=>D(s).toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'});
function schedule(day){let i=0;return periods.map(([time,fixed])=>({time,name:fixed??templates[day][i++]}))}
function tone(n){if(n==='4th')return'yellow';if(['Graham','EBS 2','Jackson','Kane','Trogdon'].includes(n))return'pink';if(['Horne','Fray','Radford','Hearley'].includes(n))return'orange';if(['Cantin','Evans','Ward','Wells','ECS'].includes(n))return'blue';if(['Alston','Edwards','Reece','Rogers'].includes(n))return'purple';if(['5th','Free','Clean Up / Prepare for carpool'].includes(n))return'green';if(n==='Lunch')return'cream';return'white'}
function getSaved(){try{return JSON.parse(localStorage.getItem(STORE))||{pushes:[],audit:[]}}catch{return{pushes:[],audit:[]}}}
export default function App(){
 const saved=getSaved(),[pushes,setPushes]=useState(saved.pushes),[audit,setAudit]=useState(saved.audit),[view,setView]=useState('today'),[selected,setSelected]=useState(START),[confirm,setConfirm]=useState(false),[online,setOnline]=useState(navigator.onLine),[waiting,setWaiting]=useState(null);const file=useRef();
 useEffect(()=>localStorage.setItem(STORE,JSON.stringify({pushes,audit})),[pushes,audit]);
 useEffect(()=>{const f=()=>setOnline(navigator.onLine);addEventListener('online',f);addEventListener('offline',f);if('serviceWorker'in navigator){navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`).then(reg=>{if(reg.waiting)setWaiting(reg.waiting);reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)setWaiting(w)})})});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload())}return()=>{removeEventListener('online',f);removeEventListener('offline',f)}},[]);
 const pushSet=useMemo(()=>new Set([...builtIn,...pushes]),[pushes]);const cal=useMemo(()=>{let c=0,o={};for(let d=D(START);d<=D(END);d=A(d,1)){const k=I(d);if([0,6].includes(d.getDay()))continue;if(closures[k])o[k]={status:closures[k]};else if(pushSet.has(k))o[k]={status:'Push Day'};else{c=c%6+1;o[k]={day:c,rows:schedule(c)}}}return o},[pushSet]);const info=cal[selected]||{status:'Outside calendar'},shift=[...pushSet].filter(x=>x<=selected).length;
 const log=(action,target)=>setAudit(a=>[{id:crypto.randomUUID?.()||String(Date.now()),at:new Date().toISOString(),action,target},...a]);
 const push=()=>{setPushes(p=>[...new Set([...p,selected])].sort());log('Push day added',selected);setConfirm(false)};const restore=d=>{setPushes(p=>p.filter(x=>x!==d));log('Push day restored',d)};const move=n=>{let d=A(D(selected),n);while(!cal[I(d)]&&I(d)>=START&&I(d)<=END)d=A(d,n);if(cal[I(d)])setSelected(I(d))};
 const backup=()=>{const b=new Blob([JSON.stringify({version:4,pushes,audit},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`art-schedule-${I(new Date())}.json`;a.click();URL.revokeObjectURL(a.href)};const importBackup=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);setPushes(x.pushes||[]);setAudit([{id:String(Date.now()),at:new Date().toISOString(),action:'Backup restored',target:I(new Date())},...(x.audit||[])])}catch{alert('Invalid backup file.')}};r.readAsText(f)};
 const tabs=[['today',Home,'Today'],['three',CalendarDays,'3 Weeks'],['settings',Settings,'Backup']];
 return <div className="app"><header><div><h1>Art Schedule</h1><small>2026-2027 six-day rotation</small></div><div className="header-actions"><span className="network">{online?<Wifi/>:<CloudOff/>}{online?'Online':'Offline'}</span><button aria-label="Print" onClick={()=>window.print()}><Printer/></button></div></header>{waiting&&<div className="update"><span>A new version is ready.</span><button onClick={()=>waiting.postMessage({type:'SKIP_WAITING'})}><RefreshCw/>Update now</button></div>}<main>{view==='today'&&<Today info={info} selected={selected} shift={shift} move={move} push={()=>setConfirm(true)} undo={()=>pushes.length&&restore(pushes.at(-1))}/>} {view==='three'&&<Three cal={cal} selected={selected} open={d=>{setSelected(d);setView('today')}}/>}{view==='settings'&&<SettingsPanel pushes={pushes} restore={restore} backup={backup} file={file} importBackup={importBackup}/>}</main><nav>{tabs.map(([id,Icon,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}><Icon/>{label}</button>)}</nav>{confirm&&<div className="modal"><div className="dialog"><h2>Confirm push day</h2><p><b>{F(selected)}</b> will become a no-class day. Every later instructional date will shift by one.</p><div><button onClick={()=>setConfirm(false)}>Cancel</button><button className="danger" onClick={push}>Confirm</button></div></div></div>}</div>
}
function Today({info,selected,shift,move,push,undo}){return <><div className="day-nav"><button onClick={()=>move(-1)}><ChevronLeft/></button><b>Cumulative shift: +{shift}</b><button onClick={()=>move(1)}><ChevronRight/></button></div><section className="today"><div className="title"><small>{F(selected)}</small><h2>{info.day?`Day ${info.day}`:info.status}</h2></div><div className="rows">{info.rows?info.rows.map(r=><div className={`row ${tone(r.name)}`} key={r.time}><span>{r.time}</span><b>{r.name}</b></div>):<p className="empty">No student classes. The rotation does not advance.</p>}</div></section><div className="actions"><button disabled={!info.day} className="danger" onClick={push}><SkipForward/>Push this day</button><button onClick={undo}><Undo2/>Undo latest</button></div></>}
function Three({cal,selected,open}){const a=D(selected),m=A(a,-((a.getDay()+6)%7)),days=[];for(let w=0;w<3;w++)for(let i=0;i<5;i++)days.push(I(A(m,w*7+i)));return <div className="three">{days.map(d=>{const x=cal[d];return <button key={d} onClick={()=>x&&open(d)}><div className="card-title"><small>{F(d)}</small><b>{x?.day?`Day ${x.day}`:x?.status||'Outside calendar'}</b></div>{x?.rows?.slice(2,7).filter((_,i)=>i!==2).map(r=><span className={tone(r.name)} key={r.time}>{r.name}</span>)}</button>})}</div>}
function Month({cal,open}){const[m,setM]=useState(D(START)),first=new Date(m.getFullYear(),m.getMonth(),1),start=A(first,-first.getDay()),cells=Array.from({length:42},(_,i)=>I(A(start,i)));return <section className="month"><div className="month-head"><button onClick={()=>setM(new Date(m.getFullYear(),m.getMonth()-1,1))}><ChevronLeft/></button><b>{m.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</b><button onClick={()=>setM(new Date(m.getFullYear(),m.getMonth()+1,1))}><ChevronRight/></button></div><div className="month-grid">{cells.map(d=>{const x=cal[d];return <button key={d} onClick={()=>x&&open(d)}><b>{D(d).getDate()}</b>{x&&<span>{x.day?`Day ${x.day}`:x.status}</span>}</button>})}</div></section>}
function SettingsPanel({pushes,restore,backup,file,importBackup}){return <section className="settings"><h2>Backup and restore</h2><p>Use this when moving the schedule to another device or before clearing Safari data.</p><div className="settings-grid"><article><h3>Schedule backup</h3><div className="actions"><button onClick={backup}><Download/>Save backup</button><button onClick={()=>file.current.click()}><FileUp/>Restore backup</button><input ref={file} type="file" accept=".json" hidden onChange={importBackup}/></div></article><article><h3>Added push days</h3><p><b>Built in:</b> September 11, 2026</p>{pushes.length===0?<p>None added.</p>:pushes.map(d=><div className="push-row" key={d}><b>{F(d)}</b><button onClick={()=>restore(d)}>Restore</button></div>)}</article></div><article><h3>Install on iPad</h3><ol><li>Open the deployed address in Safari.</li><li>Tap Share, then Add to Home Screen.</li><li>Turn on Open as Web App and tap Add.</li></ol></article></section>}
