import { useEffect, useMemo, useRef, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Download, FileUp, Home, RotateCcw, SkipForward, Undo2 } from 'lucide-react';

const START='2026-08-24', END='2027-06-09', STORE='art-pwa-v4';
const templates={1:['Free','Free','Cantin','Alston'],2:['Graham','Horne','Evans','Free'],3:['EBS 2','Fray','Ward','Edwards'],4:['Jackson','Free','Wells','Reece'],5:['Kane','Radford','Free','Rogers'],6:['Trogdon','Hearley','ECS','Free']};
const periods=[['8:00 - 8:30','Hallway Duty (not 4th grade)'],['8:50 - 9:35','4th'],['9:55 - 10:40',null],['10:50 - 11:35',null],['11:35 - 12:10','Lunch'],['12:10 - 12:55',null],['12:55 - 1:40',null],['1:40 - 2:30','5th'],['2:30 - 3:00','Clean Up / Prepare for carpool'],['3:00 - 3:30','Afternoon Carpool']];
const closures={'2026-09-07':'Holiday','2026-09-21':'Teacher Workday','2026-10-12':'Teacher Workday','2026-11-03':'Teacher Workday','2026-11-11':'Holiday','2026-11-25':'Vacation Day','2026-11-26':'Holiday','2026-11-27':'Holiday','2026-12-21':'Teacher Workday','2026-12-22':'Teacher Workday','2026-12-23':'Vacation Day','2026-12-24':'Holiday','2026-12-25':'Holiday','2026-12-28':'Holiday','2026-12-29':'Vacation Day','2026-12-30':'Vacation Day','2026-12-31':'Vacation Day','2027-01-01':'Holiday','2027-01-18':'Holiday','2027-01-19':'Teacher Workday','2027-02-15':'Teacher Workday','2027-03-10':'Teacher Workday','2027-03-26':'Holiday','2027-03-29':'Vacation Day','2027-03-30':'Vacation Day','2027-03-31':'Vacation Day','2027-04-01':'Vacation Day','2027-04-02':'Vacation Day','2027-04-05':'Teacher Workday','2027-05-17':'Teacher Workday','2027-05-31':'Holiday'};
const builtIn=['2026-09-11'];
const D=s=>{const[y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
const I=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const A=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const F=(s,o={weekday:'long',month:'long',day:'numeric',year:'numeric'})=>D(s).toLocaleDateString('en-US',o);
const initialDate=()=>{const today=I(new Date());return today<START?START:today>END?END:today};
function schedule(day){let i=0;return periods.map(([time,fixed])=>({time,name:fixed??templates[day][i++]}))}
function tone(n){if(n==='4th')return'yellow';if(['Graham','EBS 2','Jackson','Kane','Trogdon'].includes(n))return'pink';if(['Horne','Fray','Radford','Hearley'].includes(n))return'orange';if(['Cantin','Evans','Ward','Wells','ECS'].includes(n))return'blue';if(['Alston','Edwards','Reece','Rogers'].includes(n))return'purple';if(['5th','Free','Clean Up / Prepare for carpool'].includes(n))return'green';if(n==='Lunch')return'cream';return'white'}
function getSaved(){try{return JSON.parse(localStorage.getItem(STORE))||{pushes:[]}}catch{return{pushes:[]}}}
export default function App(){
 const [pushes,setPushes]=useState(()=>getSaved().pushes||[]),[view,setView]=useState('today'),[selected,setSelected]=useState(initialDate),[month,setMonth]=useState(()=>{const d=D(initialDate());return new Date(d.getFullYear(),d.getMonth(),1)}),[confirm,setConfirm]=useState(false);const file=useRef();
 useEffect(()=>localStorage.setItem(STORE,JSON.stringify({pushes})),[pushes]);
 useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`)},[]);
 const pushSet=useMemo(()=>new Set([...builtIn,...pushes]),[pushes]);
 const cal=useMemo(()=>{let c=0,o={};for(let d=D(START);d<=D(END);d=A(d,1)){const k=I(d);if([0,6].includes(d.getDay()))continue;if(closures[k])o[k]={status:closures[k]};else if(pushSet.has(k))o[k]={status:'Push Day'};else{c=c%6+1;o[k]={day:c,rows:schedule(c)}}}return o},[pushSet]);
 const info=cal[selected]||{status:'Weekend'};
 const choose=d=>{setSelected(d);setMonth(new Date(D(d).getFullYear(),D(d).getMonth(),1));setView('today')};
 const move=n=>{let d=A(D(selected),n);while(!cal[I(d)]&&I(d)>=START&&I(d)<=END)d=A(d,n);if(cal[I(d)])choose(I(d))};
 const push=()=>{setPushes(p=>[...new Set([...p,selected])].sort());setConfirm(false)};
 const undo=()=>setPushes(p=>p.slice(0,-1));
 const backup=()=>{const b=new Blob([JSON.stringify({version:4,pushes},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`art-schedule-${I(new Date())}.json`;a.click();URL.revokeObjectURL(a.href)};
 const restore=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.pushes))throw Error();setPushes(x.pushes)}catch{alert('Invalid backup file.')}};r.readAsText(f);e.target.value=''};
 const tabs=[['today',Home,'Today'],['three',CalendarDays,'3 Weeks'],['calendar',CalendarDays,'Calendar'],['backup',RotateCcw,'Backup']];
 return <div className="app"><header><div><h1>Art Schedule</h1><small>2026-2027 six-day rotation</small></div><button onClick={()=>choose(initialDate())}>Today</button></header><main>
 {view==='today'&&<><div className="day-nav"><button onClick={()=>move(-1)}><ChevronLeft/></button><b>{F(selected,{month:'short',day:'numeric',year:'numeric'})}</b><button onClick={()=>move(1)}><ChevronRight/></button></div><section className="today"><div className={`title ${info.status?'closed':''}`}><small>{F(selected)}</small><h2>{info.day?`Day ${info.day}`:info.status}</h2></div><div className="rows">{info.rows?info.rows.map(r=><div className={`row ${tone(r.name)}`} key={r.time}><span>{r.time}</span><b>{r.name}</b></div>):<p className="empty">No student classes. The rotation does not advance.</p>}</div></section><div className="actions"><button disabled={!info.day} className="danger" onClick={()=>setConfirm(true)}><SkipForward/>Push this day</button><button disabled={!pushes.length} onClick={undo}><Undo2/>Undo push</button></div></>}
 {view==='three'&&<Three cal={cal} selected={selected} open={choose}/>} 
 {view==='calendar'&&<Month cal={cal} month={month} setMonth={setMonth} open={choose}/>} 
 {view==='backup'&&<section className="settings"><h2>Backup and restore</h2><p>Save a backup before clearing Safari data or moving to another iPad.</p><div className="actions"><button onClick={backup}><Download/>Save backup</button><button onClick={()=>file.current.click()}><FileUp/>Restore backup</button><input ref={file} type="file" accept=".json" hidden onChange={restore}/></div><article><h3>Added push days</h3><p><b>Built in:</b> September 11, 2026</p>{pushes.length?pushes.map(d=><p key={d}>{F(d)}</p>):<p>None added.</p>}</article></section>}
 </main><nav>{tabs.map(([id,Icon,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}><Icon/>{label}</button>)}</nav>{confirm&&<div className="modal"><div className="dialog"><h2>Push this day?</h2><p><b>{F(selected)}</b> will become a no-class day. Every later date will shift by one.</p><div><button onClick={()=>setConfirm(false)}>Cancel</button><button className="danger" onClick={push}>Yes, push it</button></div></div></div>}</div>
}
function Three({cal,selected,open}){const a=D(selected),m=A(a,-((a.getDay()+6)%7)),days=[];for(let w=0;w<3;w++)for(let i=0;i<5;i++)days.push(I(A(m,w*7+i)));return <section><h2>Three-week view</h2><div className="three">{days.map(d=>{const x=cal[d];return <button key={d} onClick={()=>x&&open(d)}><div className={`card-title ${x?.status?'closed':''}`}><small>{F(d,{weekday:'short',month:'short',day:'numeric'})}</small><b>{x?.day?`Day ${x.day}`:x?.status||'Weekend'}</b></div>{x?.rows?.slice(2,7).filter((_,i)=>i!==2).map(r=><span className={tone(r.name)} key={r.time}>{r.name}</span>)}</button>})}</div></section>}
function Month({cal,month,setMonth,open}){const first=new Date(month.getFullYear(),month.getMonth(),1),start=A(first,-first.getDay()),cells=Array.from({length:42},(_,i)=>I(A(start,i)));return <section className="month"><div className="month-head"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft/></button><h2>{month.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</h2><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight/></button></div><div className="weekdays">{'SMTWTFS'.split('').map((d,i)=><b key={i}>{d}</b>)}</div><div className="month-grid">{cells.map(d=>{const x=cal[d],same=D(d).getMonth()===month.getMonth(),inYear=d>=START&&d<=END;return <button key={d} disabled={!inYear} className={`${same?'':'other'} ${d===I(new Date())?'is-today':''}`} onClick={()=>open(d)}><b>{D(d).getDate()}</b>{x?.day&&<span className="school">Day {x.day}</span>}{x?.status&&<span className="closure">{x.status}</span>}{inYear&&!x&&<span className="weekend">Weekend</span>}</button>})}</div></section>}
